version: "3.5"
services:
  develop:
    build: .
    container_name: fw-contextual-layer-develop
    ports:
        - "3025:3025"
    environment:
      PORT: 3025
      NODE_ENV: dev
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CT_URL: https://staging-api.resourcewatch.org
      LOCAL_URL: http://127.0.0.1:3025
      TEAMS_API_URL: https://staging-api.resourcewatch.org/v1
      MONGO_PORT_27017_TCP_ADDR: mongo
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: fw_contextual_layer
      API_VERSION: v1
    volumes:
      - ./app:/opt/fw-contextual-layer/app
      - ./nodemon.json:/opt/fw-contextual-layer/nodemon.json
    depends_on:
      - mongo
    networks:
      - gfw-network
      - gfw-contextual-layers-network
    command: yarn dev

  test:
    build: .
    container_name: fw-contextual-layer-test
    environment:
      PORT: 0
      NODE_ENV: test
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CT_URL: http://127.0.0.1:9000
      LOCAL_URL: http://127.0.0.1:3025
      TEAMS_API_URL: http://fw-teams-develop:3035/api/v1
      MONGO_PORT_27017_TCP_ADDR: mongo
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: fw_contextual_layer
      API_VERSION: v1
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/fw-contextual-layer/app
      - ./nodemon.json:/opt/fw-contextual-layer/nodemon.json
      - ./jest.config.js:/opt/fw-contextual-layer/jest.config.js
    command: yarn test

  docs:
    build: .
    ports:
      - "30250:30250"
    container_name: fw-contextual-layer-docs
    volumes:
      - ./docs:/opt/fw-contextual-layer/docs
    command: yarn run docs -l 30250

  mongo:
    image: mongo:3.4
    container_name: fw-contextual-layer-mongo-develop
    command: --smallfiles
    ports:
      - "27023:27017"
    environment:
      MONGO_INITDB_DATABASE: fw_contextual_layer
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - fw-contextual-layer-mongodb-data:/data/db
    restart: always
    networks:
      - gfw-contextual-layers-network

volumes:
  fw-contextual-layer-mongodb-data:

networks:
  gfw-network:
    name: gfw-network
  gfw-contextual-layers-network:
    name: gfw-contextual-layers-network
