version: "3"
services:
  test:
    build: .
    ports:
      - "3025:3025"
    container_name: fw-contextual-layer-test
    environment:
      PORT: 3025
      NODE_PATH: app/src
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      MONGO_PORT_27017_TCP_ADDR: mongo
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      LOCAL_URL: http://mymachine:3055
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: test
    depends_on:
      - mongo

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"
