version: "3"
services:
  test:
    build: .
    container_name: fw-contextual-layer-test
    ports:
      - "3025:3025"
    environment:
      PORT: 3025
      NODE_PATH: app/src
      NODE_ENV: test
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CONTROL_TOWER_URL: http://127.0.0.1:9000
      LOCAL_URL: http://127.0.0.1:3025
      TEAMS_API_URL: http://fw-teams-develop:3035/api/v1
      MONGO_PORT_27017_TCP_ADDR: mongo
      API_VERSION: v1
    depends_on:
      - mongo
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js e2eTest

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"
