apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: fw
  name: fw-contextual-layers
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: fw-contextual-layers
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
